import { Project, Stat } from './types';

export const BACKUP_IMAGES = [
  'https://images.unsplash.com/photo-1579165466741-7f35a4755657?auto=format&fit=crop&w=800&q=80', // Microscope/Lab
  'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80', // Research/Pipette
  'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80', // Purple/Pink Cells
  'https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=800&q=80', // Blue Cells
  'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=800&q=80', // DNA Structure
  'https://images.unsplash.com/photo-1581093458891-8f30869852cd?auto=format&fit=crop&w=800&q=80', // Scientist Data
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80', // Medicine/Pills
  'https://images.unsplash.com/photo-1631553127888-29007c082356?auto=format&fit=crop&w=800&q=80', // Abstract DNA
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=800&q=80', // Vials
  'https://images.unsplash.com/photo-1559757175-57719c30b314?auto=format&fit=crop&w=800&q=80', // Abstract Brain/Cells
];

export const FEATURED_PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'Mitochondrial Rescue in Leigh Syndrome via Repurposed FDA Compounds',
    simpleTitle: 'Restoring Energy to Brain Cells',
    brief: 'Completing preclinical IND-enabling studies for a novel metabolic modulator that restores ATP production in patient-derived neuronal organoids.',
    simpleBrief: 'We are testing a safe, existing medicine that helps brain cells produce the energy they need to survive and function.',
    imagePrompt: 'A photorealistic macro close-up of neuronal cells glowing with bright golden energy, symbolizing restored mitochondrial function, against a deep blue medical background. High definition, scientific visualization.',
    category: 'Drug Repurposing',
    imageUrl: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=800&q=80', // Cells
    researcher: {
      id: 'r1',
      name: 'Dr. James Chen',
      title: 'Assistant Professor of Neurology',
      institution: 'UCSF Weill Institute for Neurosciences',
      avatarUrl: 'https://picsum.photos/id/1005/200/200',
      verified: true,
    },
    fundingGoal: 80000,
    fundingRaised: 47500,
    backersCount: 142,
    milestonesCompleted: 1,
    totalMilestones: 3,
    milestones: ['In-vitro validation', 'Safety profile', 'IND Application']
  },
  {
    id: 'p2',
    title: 'Precision Gene Editing for 22q11.2 Deletion Syndrome',
    simpleTitle: 'Fixing the Missing Gene in 22q',
    brief: 'Developing a brain-penetrant viral vector to deliver CRISPR-Cas9 machinery specifically to cortical interneurons to correct haploinsufficiency.',
    simpleBrief: 'A one-time gene treatment designed to restore the missing DNA in a child’s brain and correct developmental delays.',
    imagePrompt: 'A 3D artistic representation of a DNA double helix with a glowing green segment being repaired by a futuristic molecular tool, representing CRISPR editing. Soft lighting, hopeful atmosphere.',
    category: 'Gene Therapy',
    imageUrl: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=800&q=80', // DNA
    researcher: {
      id: 'r2',
      name: 'Dr. Elena Vasquez',
      title: 'Principal Investigator',
      institution: 'Stanford School of Medicine',
      avatarUrl: 'https://picsum.photos/id/1011/200/200',
      verified: true,
    },
    fundingGoal: 150000,
    fundingRaised: 12500,
    backersCount: 34,
    milestonesCompleted: 0,
    totalMilestones: 4,
    milestones: ['Vector Design', 'Mouse Model Testing']
  },
  {
    id: 'p3',
    title: 'Neuroprotective Cooling 2.0 for HIE Neonates',
    simpleTitle: 'Saving Newborns from Oxygen Loss',
    brief: 'A pilot study investigating a synergistic pharmacological cocktail combined with therapeutic hypothermia to reduce brain injury after birth asphyxia.',
    simpleBrief: 'Improving the standard cooling therapy to better protect newborn babies who suffered oxygen deprivation at birth.',
    imagePrompt: 'A conceptual illustration of a newborn infant sleeping peacefully, surrounded by a protective, icy-blue aura shield that represents neuroprotection. Soft, gentle, comforting medical art.',
    category: 'Clinical Trial',
    imageUrl: 'https://images.unsplash.com/photo-1551884170-09fb70a3a2ed?auto=format&fit=crop&w=800&q=80', // Abstract Medical Blue
    researcher: {
      id: 'r3',
      name: 'Dr. Sarah Miller',
      title: 'Director of Neonatal Research',
      institution: 'Boston Children\'s Hospital',
      avatarUrl: 'https://picsum.photos/id/338/200/200',
      verified: true,
    },
    fundingGoal: 75000,
    fundingRaised: 68000,
    backersCount: 210,
    milestonesCompleted: 2,
    totalMilestones: 3,
    milestones: ['Phase I Recruitment', 'Data Analysis']
  },
  {
    id: 'p4',
    title: 'Cognitive Enhancement in Down Syndrome: A Kinase Inhibitor Approach',
    simpleTitle: 'Improving Memory in Down Syndrome',
    brief: 'Investigating a novel DYRK1A inhibitor to improve memory and learning capabilities in adult mouse models of Down Syndrome.',
    simpleBrief: 'Developing a daily medication that could improve learning, memory, and speech in people with Down Syndrome.',
    imagePrompt: 'A stylized illustration of a brain lighting up with intricate, bright connections in the hippocampus region, symbolizing improved memory and cognition. Modern, clean vector art style.',
    category: 'Basic Science',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-57719c30b314?auto=format&fit=crop&w=800&q=80', // Brain
    researcher: {
      id: 'r4',
      name: 'Dr. Robert Liu',
      title: 'Picower Professor of Neuroscience',
      institution: 'MIT',
      avatarUrl: 'https://picsum.photos/id/1025/200/200',
      verified: true,
    },
    fundingGoal: 120000,
    fundingRaised: 15000,
    backersCount: 18,
    milestonesCompleted: 1,
    totalMilestones: 5,
    milestones: ['Compound Synthesis', 'Behavioral Assays']
  },
  {
    id: 'p5',
    title: 'Stem Cell Therapy for Periventricular Leukomalacia (Cerebral Palsy)',
    simpleTitle: 'Repairing Brain Injury in Cerebral Palsy',
    brief: 'Transplanting oligodendrocyte precursor cells derived from iPSCs to remyelinate damaged white matter in early-stage CP models.',
    simpleBrief: 'Using healthy stem cells to replace the damaged tissue in the brains of children with Cerebral Palsy.',
    imagePrompt: 'Microscopic view of stem cells transforming into neurons, with delicate tendrils connecting and forming a network. Vibrant teals and purples. High-end scientific visualization.',
    category: 'Disease Modeling',
    imageUrl: 'https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=800&q=80', // Stem Cells/Lab
    researcher: {
      id: 'r5',
      name: 'Dr. Amara Okania',
      title: 'Associate Professor',
      institution: 'Johns Hopkins Medicine',
      avatarUrl: 'https://picsum.photos/id/1027/200/200',
      verified: true,
    },
    fundingGoal: 200000,
    fundingRaised: 89000,
    backersCount: 312,
    milestonesCompleted: 1,
    totalMilestones: 4,
    milestones: ['Cell Line Generation', 'Engraftment Study']
  },
  {
    id: 'p6',
    title: 'Re-activating MECP2 in Rett Syndrome Organoids',
    simpleTitle: 'Waking Up the Silent Gene in Rett Syndrome',
    brief: 'Screening a library of small molecules to identify compounds that can reactivate the silent X-chromosome MECP2 allele.',
    simpleBrief: 'Finding a drug that switches on the healthy backup gene that every girl with Rett Syndrome already has.',
    imagePrompt: 'A close-up of a double X chromosome, where one X is glowing bright warm orange, symbolizing reactivation. Cinematic lighting, medical 3D render.',
    category: 'Drug Repurposing',
    imageUrl: 'https://images.unsplash.com/photo-1631553127888-29007c082356?auto=format&fit=crop&w=800&q=80', // DNA Abstract
    researcher: {
      id: 'r6',
      name: 'Dr. Emily Weiss',
      title: 'Director of Genetics',
      institution: 'Baylor College of Medicine',
      avatarUrl: 'https://picsum.photos/id/342/200/200',
      verified: true,
    },
    fundingGoal: 95000,
    fundingRaised: 92500,
    backersCount: 405,
    milestonesCompleted: 3,
    totalMilestones: 4,
    milestones: ['Screening', 'Hit Validation']
  },
  {
    id: 'p7',
    title: 'GD2-Targeted CAR-T Cells for Diffuse Intrinsic Pontine Glioma (DIPG)',
    simpleTitle: 'Immune Therapy for Deadly Brain Tumors',
    brief: 'A Phase I clinical trial using 4th generation CAR-T cells to target the aggressive brain tumor DIPG, which currently has a 0% survival rate.',
    simpleBrief: 'Engineering the child’s own immune cells to recognize, hunt down, and destroy this currently incurable brain tumor.',
    imagePrompt: 'Futuristic T-cells attacking a tumor mass, depicted as glowing warrior cells swarming a dark, textured anomaly. Dynamic action, microscopic battlefield, immunotherapy concept.',
    category: 'Clinical Trial',
    imageUrl: 'https://images.unsplash.com/photo-1579165466741-7f35a4755657?auto=format&fit=crop&w=800&q=80', // Medical Research
    researcher: {
      id: 'r7',
      name: 'Dr. Michael H. Chang',
      title: 'Director of Pediatric Neuro-oncology',
      institution: 'Sloan Kettering Institute',
      avatarUrl: 'https://picsum.photos/id/1012/200/200',
      verified: true,
    },
    fundingGoal: 250000,
    fundingRaised: 45000,
    backersCount: 204,
    milestonesCompleted: 1,
    totalMilestones: 5,
    milestones: ['Vector Manufacturing', 'Patient Enrollment']
  },
  {
    id: 'p8',
    title: 'Crossing the Barrier: Enzyme Therapy for Sanfilippo Syndrome Type A',
    simpleTitle: 'Delivering the Missing Enzyme to the Brain',
    brief: 'Developing a "Trojan Horse" fusion protein to transport the missing SGSH enzyme across the blood-brain barrier.',
    simpleBrief: 'A new delivery system to get the essential missing enzyme into the brain to stop neurodegeneration in Sanfilippo Syndrome.',
    imagePrompt: 'An abstract representation of the blood-brain barrier as a glowing filter, with specialized carrier molecules transporting bright therapeutic payloads through it. High-tech medical visualization.',
    category: 'Gene Therapy',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=800&q=80', // Brain/Barrier
    researcher: {
      id: 'r8',
      name: 'Dr. Sarah Bennett',
      title: 'Associate Professor of Genetics',
      institution: 'UNC Chapel Hill',
      avatarUrl: 'https://picsum.photos/id/1024/200/200',
      verified: true,
    },
    fundingGoal: 110000,
    fundingRaised: 32000,
    backersCount: 88,
    milestonesCompleted: 0,
    totalMilestones: 3,
    milestones: ['Vector Design', 'Mouse Model Efficacy']
  },
  {
    id: 'p9',
    title: 'Awakening the Sleeping Gene: CRISPR-dCas9 for Angelman Syndrome',
    simpleTitle: 'Turning On the Silent Gene in Angelman',
    brief: 'Using epigenome editing to unsilence the dormant paternal UBE3A allele in neurons.',
    simpleBrief: 'Using advanced gene editing to "wake up" the sleeping father copy of the gene to cure Angelman Syndrome.',
    imagePrompt: 'A stylized DNA strand where a shadowed section is being illuminated by a bright light source, representing gene unsilencing. Hopeful, clean, modern design.',
    category: 'Gene Therapy',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80', // Lab
    researcher: {
      id: 'r9',
      name: 'Dr. Yvette Cole',
      title: 'Principal Investigator',
      institution: 'UC Davis MIND Institute',
      avatarUrl: 'https://picsum.photos/id/1013/200/200',
      verified: true,
    },
    fundingGoal: 180000,
    fundingRaised: 165000,
    backersCount: 412,
    milestonesCompleted: 2,
    totalMilestones: 3,
    milestones: ['Epigenetic Screening', 'iPSC Validation']
  },
  {
    id: 'p10',
    title: 'Stopping Blindness and Seizures in CLN3 Batten Disease',
    simpleTitle: 'Saving Vision in Batten Disease',
    brief: 'Preclinical testing of a novel antisense oligonucleotide (ASO) designed to correct the common 1kb deletion splicing error in CLN3.',
    simpleBrief: 'A genetic patch designed to stop vision loss and seizures in children with CLN3 Batten Disease.',
    imagePrompt: 'A close up of a human eye with a digital, schematic overlay of the retina being repaired. Futuristic, cyber-medical aesthetic, blue and silver tones.',
    category: 'Gene Therapy',
    imageUrl: 'https://images.unsplash.com/photo-1580256081112-e49377338b7f?auto=format&fit=crop&w=800&q=80', // Eye
    researcher: {
      id: 'r10',
      name: 'Dr. David Anderson',
      title: 'Professor of Ophthalmology',
      institution: 'University of Rochester',
      avatarUrl: 'https://picsum.photos/id/1009/200/200',
      verified: true,
    },
    fundingGoal: 90000,
    fundingRaised: 12000,
    backersCount: 41,
    milestonesCompleted: 1,
    totalMilestones: 4,
    milestones: ['ASO Design', 'Safety Testing']
  },
  {
    id: 'p11',
    title: 'Gene Replacement Strategy for FOXG1 Syndrome',
    simpleTitle: 'Gene Therapy for FOXG1',
    brief: 'Optimizing viral capsid serotypes to deliver a healthy copy of the FOXG1 gene specifically to forebrain GABAergic interneurons.',
    simpleBrief: 'Replacing the broken FOXG1 gene with a healthy copy to restore normal brain development.',
    imagePrompt: 'A translucent, glowing brain model showing specific areas (forebrain) lighting up with therapeutic activity. 3D render, educational and scientific.',
    category: 'Basic Science',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=800&q=80', // Brain
    researcher: {
      id: 'r11',
      name: 'Dr. Priya Patel',
      title: 'Assistant Professor',
      institution: 'Harvard Medical School',
      avatarUrl: 'https://picsum.photos/id/1049/200/200',
      verified: true,
    },
    fundingGoal: 135000,
    fundingRaised: 67000,
    backersCount: 156,
    milestonesCompleted: 1,
    totalMilestones: 3,
    milestones: ['Capsid Selection', 'Dose Ranging']
  },
  {
    id: 'p12',
    title: 'Precision Drug Screening on SCN2A-Deficient Cortical Organoids',
    simpleTitle: 'Finding Epilepsy Drugs with "Mini-Brains"',
    brief: 'Creating patient-specific brain organoids to screen a library of 2,000 FDA-approved compounds for their ability to restore normal firing patterns.',
    simpleBrief: 'Testing thousands of existing safe drugs on lab-grown "mini-brains" to find one that stops seizures in SCN2A.',
    imagePrompt: 'A laboratory array of tiny, floating "mini-brains" (organoids) in a multi-well plate, under soft violet examination light. Macro photography style.',
    category: 'Disease Modeling',
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80', // Microscope
    researcher: {
      id: 'r12',
      name: 'Dr. Marcus Thorne',
      title: 'Senior Group Leader',
      institution: 'The Francis Crick Institute',
      avatarUrl: 'https://picsum.photos/id/1053/200/200',
      verified: true,
    },
    fundingGoal: 65000,
    fundingRaised: 64000,
    backersCount: 220,
    milestonesCompleted: 2,
    totalMilestones: 2,
    milestones: ['Organoid Generation', 'High-Throughput Screen']
  },
  {
    id: 'p13',
    title: 'Up-regulating SYNGAP1 Expression via t-RNA Therapeutics',
    simpleTitle: 'A New Way to Boost SYNGAP1 Levels',
    brief: 'A novel approach using suppressor t-RNAs to read through premature stop mutations in SYNGAP1 patients.',
    simpleBrief: 'Using a special molecule to trick the cell into ignoring the "stop" signal caused by the mutation, allowing the protein to be made.',
    imagePrompt: 'Detailed molecular diagram of a ribosome reading RNA, with a special glowing "key" molecule allowing it to bypass a barrier. Instructional, high-quality 3D render.',
    category: 'Drug Repurposing',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80', // Lab
    researcher: {
      id: 'r13',
      name: 'Dr. Emily Zhao',
      title: 'Postdoctoral Fellow',
      institution: 'Baylor College of Medicine',
      avatarUrl: 'https://picsum.photos/id/1062/200/200',
      verified: true,
    },
    fundingGoal: 40000,
    fundingRaised: 1500,
    backersCount: 12,
    milestonesCompleted: 0,
    totalMilestones: 3,
    milestones: ['tRNA Synthesis', 'Cellular Assays']
  },
  {
    id: 'p14',
    title: 'Next-Generation Potassium Channel Openers for KCNQ2 Encephalopathy',
    simpleTitle: 'Better Seizure Control for KCNQ2',
    brief: 'Synthesizing and testing selective Kv7.2/7.3 activators that lack the side effects of retigabine.',
    simpleBrief: 'Creating a safer, more effective medicine to stop seizures in babies with KCNQ2 epilepsy without the bad side effects of older drugs.',
    imagePrompt: 'Artist rendering of an ion channel in a cell membrane opening to let glowing ions flow through, stabilizing the cell. Dynamic, fluid, cellular biology art.',
    category: 'Basic Science',
    imageUrl: 'https://images.unsplash.com/photo-1564325724739-bae0bd08762c?auto=format&fit=crop&w=800&q=80', // Chemistry/Molecule
    researcher: {
      id: 'r14',
      name: 'Dr. Thomas Keller',
      title: 'Associate Professor',
      institution: 'Northwestern University',
      avatarUrl: 'https://picsum.photos/id/1074/200/200',
      verified: true,
    },
    fundingGoal: 100000,
    fundingRaised: 45000,
    backersCount: 95,
    milestonesCompleted: 2,
    totalMilestones: 5,
    milestones: ['Compound Synthesis', 'Electrophysiology']
  },
  {
    id: 'p15',
    title: 'Beyond Survival: Enhancing Muscle Regeneration in SMA',
    simpleTitle: 'Rebuilding Muscle in SMA',
    brief: 'Investigating myostatin inhibitors combined with SMN restoration to rebuild lost muscle mass in older SMA patients.',
    simpleBrief: 'Helping patients with SMA get stronger by using a drug that encourages muscle growth alongside their gene therapy.',
    imagePrompt: 'Cross-section of muscle fibers rebuilding and strengthening, glowing with vitality. Medical illustration showing regeneration and strength.',
    category: 'Clinical Trial',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=800&q=80', // Fitness/Muscle
    researcher: {
      id: 'r15',
      name: 'Dr. Linda Wei',
      title: 'Director of Neuromuscular Research',
      institution: 'Columbia University',
      avatarUrl: 'https://picsum.photos/id/334/200/200',
      verified: true,
    },
    fundingGoal: 160000,
    fundingRaised: 155000,
    backersCount: 302,
    milestonesCompleted: 3,
    totalMilestones: 4,
    milestones: ['Drug Combination Study', 'Clinical Protocol']
  },
  {
    id: 'p16',
    title: 'Chemical Chaperones to Stabilize STXBP1 Protein Folding',
    simpleTitle: 'Stabilizing the Protein in STXBP1',
    brief: 'Identifying small molecules that help mutant STXBP1 proteins fold correctly, preventing their degradation.',
    simpleBrief: 'Finding a "helper" drug that holds the protein in the right shape so it can do its job in the brain.',
    imagePrompt: 'A 3D visualization of a complex protein folding into the correct shape with the help of small glowing stabilizer molecules. Elegant, structural biology art.',
    category: 'Drug Repurposing',
    imageUrl: 'https://images.unsplash.com/photo-1624726175512-19b9baf00ca9?auto=format&fit=crop&w=800&q=80', // Abstract Geometric/Protein
    researcher: {
      id: 'r16',
      name: 'Dr. Robert S. Miller',
      title: 'Professor of Neuroscience',
      institution: 'University of Pennsylvania',
      avatarUrl: 'https://picsum.photos/id/15/200/200',
      verified: true,
    },
    fundingGoal: 55000,
    fundingRaised: 22000,
    backersCount: 65,
    milestonesCompleted: 1,
    totalMilestones: 3,
    milestones: ['Screening', 'Hit Optimization']
  },
  {
    id: 'p17',
    title: 'Reversing FMR1 Silencing with Targeted Demethylation',
    simpleTitle: 'Reversing Fragile X Syndrome',
    brief: 'Using a dCas9-Tet1 complex to remove methylation marks from the FMR1 promoter, reactivating the gene.',
    simpleBrief: 'Removing the chemical "off switch" that silences the gene in Fragile X, allowing the brain to develop normally.',
    imagePrompt: 'A close-up of a DNA strand where heavy, dark "tags" (methylation) are being removed by a molecular tool, revealing the clean, active gene underneath. Conceptual gene editing art.',
    category: 'Gene Therapy',
    imageUrl: 'https://images.unsplash.com/photo-1633613286991-611fe299c4be?auto=format&fit=crop&w=800&q=80', // DNA
    researcher: {
      id: 'r17',
      name: 'Dr. Jessica Alverez',
      title: 'Principal Investigator',
      institution: 'Emory University',
      avatarUrl: 'https://picsum.photos/id/65/200/200',
      verified: true,
    },
    fundingGoal: 125000,
    fundingRaised: 98000,
    backersCount: 180,
    milestonesCompleted: 2,
    totalMilestones: 5,
    milestones: ['Vector Construction', 'Methylation Analysis']
  },
  {
    id: 'p18',
    title: 'AAV-Mediated Gene Therapy for CDKL5 Deficiency Disorder',
    simpleTitle: 'Gene Therapy for CDKL5',
    brief: 'Final IND-enabling toxicity studies for a brain-wide gene replacement therapy for CDKL5.',
    simpleBrief: 'The final safety tests needed before we can start a clinical trial to replace the missing gene in children with CDKL5.',
    imagePrompt: 'A whole brain scan visualization showing widespread, uniform distribution of a therapeutic agent (glowing green) reaching all areas. Medical imaging style.',
    category: 'Gene Therapy',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=800&q=80', // Brain
    researcher: {
      id: 'r18',
      name: 'Dr. William Grant',
      title: 'Director',
      institution: 'Children\'s Hospital of Philadelphia (CHOP)',
      avatarUrl: 'https://picsum.photos/id/55/200/200',
      verified: true,
    },
    fundingGoal: 300000,
    fundingRaised: 280000,
    backersCount: 560,
    milestonesCompleted: 4,
    totalMilestones: 5,
    milestones: ['Tox Studies', 'FDA Meeting']
  },
  {
    id: 'p19',
    title: 'Triple-Combination Therapy for Niemann-Pick Type C',
    simpleTitle: 'A Drug Cocktail for Niemann-Pick C',
    brief: 'Evaluating the synergy of miglustat, cyclodextrin, and a novel heat shock protein inducer to clear cholesterol accumulation.',
    simpleBrief: 'Testing a powerful combination of three drugs to clear the toxic buildup in cells and save children with NPC.',
    category: 'Drug Repurposing',
    imagePrompt: 'A cellular view showing a lysosome being cleared of accumulated debris/crystals, becoming clean and functional. Before and after concept blended into one image. Scientific diagram style.',
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=800&q=80', // Lab
    researcher: {
      id: 'r19',
      name: 'Dr. Hans Mueller',
      title: 'Senior Investigator',
      institution: 'NIH / NINDS',
      avatarUrl: 'https://picsum.photos/id/12/200/200',
      verified: true,
    },
    fundingGoal: 70000,
    fundingRaised: 10000,
    backersCount: 15,
    milestonesCompleted: 0,
    totalMilestones: 3,
    milestones: ['Combination Screening', 'Mouse Efficacy']
  },
  {
    id: 'p20',
    title: 'CRISPR-Cas9 Exon Editing for Duchenne Muscular Dystrophy',
    simpleTitle: 'Permanent Gene Editing for DMD',
    brief: 'Developing a permanent gene-editing strategy to remove the mutated exon 51 in DMD patients.',
    simpleBrief: 'Using CRISPR to permanently cut out the bad part of the gene so muscles can work again in Duchenne Muscular Dystrophy.',
    imagePrompt: 'A strong, healthy muscle fiber strand, with a holographic DNA overlay showing a successful gene splice. symbolizing strength and genetic repair.',
    category: 'Gene Therapy',
    imageUrl: 'https://images.unsplash.com/photo-1631553127888-29007c082356?auto=format&fit=crop&w=800&q=80', // DNA
    researcher: {
      id: 'r20',
      name: 'Dr. Carlos Mendez',
      title: 'Professor',
      institution: 'UCLA',
      avatarUrl: 'https://picsum.photos/id/32/200/200',
      verified: true,
    },
    fundingGoal: 200000,
    fundingRaised: 45000,
    backersCount: 110,
    milestonesCompleted: 1,
    totalMilestones: 5,
    milestones: ['gRNA Design', 'Muscle Cell Editing']
  },
  {
    id: 'p21',
    title: 'Silencing Toxic GFAP in Alexander Disease',
    simpleTitle: 'Stopping the Toxic Protein in Alexander Disease',
    brief: 'Developing an RNAi therapy to suppress GFAP production, aiming to clear Rosenthal fibers.',
    simpleBrief: 'A therapy that turns off the production of the toxic protein that destroys the brain in Alexander Disease.',
    imagePrompt: 'A neural network where the "static" or "noise" (toxic protein) is being quieted down, leaving clear, clean signal transmission. Conceptual abstract medical art.',
    category: 'Gene Therapy',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-57719c30b314?auto=format&fit=crop&w=800&q=80', // Neural
    researcher: {
      id: 'r21',
      name: 'Dr. Jennifer Wu',
      title: 'Associate Professor',
      institution: 'Waisman Center',
      avatarUrl: 'https://picsum.photos/id/10/200/200',
      verified: true,
    },
    fundingGoal: 115000,
    fundingRaised: 88000,
    backersCount: 201,
    milestonesCompleted: 2,
    totalMilestones: 3,
    milestones: ['siRNA Selection', 'Mouse Model Test']
  },
  {
    id: 'p22',
    title: 'Hypoxia as a Therapy for Mitochondrial Disease',
    simpleTitle: 'Oxygen Therapy for Leigh Syndrome',
    brief: 'Investigating the paradoxical finding that chronic mild hypoxia significantly extends survival in Leigh Syndrome models.',
    simpleBrief: 'Exploring a groundbreaking discovery that slightly lowering oxygen levels can actually help children with mitochondrial disease live longer.',
    imagePrompt: 'A conceptual landscape of a mountain peak at high altitude, with a glowing vitality aura, representing the paradox of hypoxia helping mitochondrial function. Atmospheric and inspiring.',
    category: 'Basic Science',
    imageUrl: 'https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=800&q=80', // Lab
    researcher: {
      id: 'r22',
      name: 'Dr. Vikram Singh',
      title: 'Investigator',
      institution: 'Massachusetts General Hospital',
      avatarUrl: 'https://picsum.photos/id/61/200/200',
      verified: true,
    },
    fundingGoal: 150000,
    fundingRaised: 75000,
    backersCount: 134,
    milestonesCompleted: 1,
    totalMilestones: 2,
    milestones: ['Hypoxia Chamber Study', 'Metabolomics']
  },
  {
    id: 'p23',
    title: 'Gene-Corrected Stem Cell Transplant for Krabbe Disease',
    simpleTitle: 'Super-Charged Stem Cells for Krabbe',
    brief: 'Combining viral gene therapy with autologous stem cell transplantation to deliver super-physiological levels of GALC enzyme.',
    simpleBrief: 'Modifying a child\'s own stem cells to produce massive amounts of the missing enzyme and save their brain.',
    imagePrompt: 'A stream of glowing, golden stem cells flowing into a brain structure, illuminating it from within. Symbolizing replacement and healing.',
    category: 'Clinical Trial',
    imageUrl: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=800&q=80', // Surgery/Transplant
    researcher: {
      id: 'r23',
      name: 'Dr. Elizabeth Horn',
      title: 'Director of BMT',
      institution: 'Duke University',
      avatarUrl: 'https://picsum.photos/id/75/200/200',
      verified: true,
    },
    fundingGoal: 400000,
    fundingRaised: 310000,
    backersCount: 780,
    milestonesCompleted: 3,
    totalMilestones: 5,
    milestones: ['IND Filing', 'Patient Recruitment']
  },
  {
    id: 'p24',
    title: 'Oxytocin Analogs for Hyperphagia in Prader-Willi Syndrome',
    simpleTitle: 'Controlling Hunger in Prader-Willi',
    brief: 'Phase II clinical trial testing a highly specific oxytocin receptor agonist to control life-threatening hyperphagia.',
    simpleBrief: 'A clinical trial for a new medicine that stops the uncontrollable, life-threatening hunger in Prader-Willi Syndrome.',
    imagePrompt: 'A stylized brain showing the hypothalamus region (hunger control center) glowing with a calming blue light, representing balance and control. Medical diagram style.',
    category: 'Clinical Trial',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-57719c30b314?auto=format&fit=crop&w=800&q=80', // Brain
    researcher: {
      id: 'r24',
      name: 'Dr. Mark Thompson',
      title: 'Professor',
      institution: 'University of Florida',
      avatarUrl: 'https://picsum.photos/id/88/200/200',
      verified: true,
    },
    fundingGoal: 180000,
    fundingRaised: 18000,
    backersCount: 30,
    milestonesCompleted: 0,
    totalMilestones: 3,
    milestones: ['Phase II Start', 'Interim Analysis']
  },
  {
    id: 'p25',
    title: 'Dual-Vector Gene Therapy for Usher Syndrome Type 1B',
    simpleTitle: 'Curing Deafness and Blindness in Usher',
    brief: 'Developing a dual-vector system that recombines inside the cell to treat both deafness and blindness in Usher Syndrome.',
    simpleBrief: 'A new way to deliver a very large gene to the eye and ear to stop children from going deaf and blind.',
    imagePrompt: 'A split artistic view showing an eye and an inner ear structure, both connected by a glowing genetic strand being repaired simultaneously. Symmetrical, balanced composition.',
    category: 'Gene Therapy',
    imageUrl: 'https://images.unsplash.com/photo-1628169222668-3561b6c0733d?auto=format&fit=crop&w=800&q=80', // Eye
    researcher: {
      id: 'r25',
      name: 'Dr. Laura Chen',
      title: 'Assistant Professor',
      institution: 'Casey Eye Institute',
      avatarUrl: 'https://picsum.photos/id/90/200/200',
      verified: true,
    },
    fundingGoal: 95000,
    fundingRaised: 42000,
    backersCount: 99,
    milestonesCompleted: 1,
    totalMilestones: 4,
    milestones: ['Vector Optimization', 'Retinal Explant Test']
  },
  {
    id: 'p26',
    title: 'Next-Gen AAV Capsids for Canavan Disease',
    simpleTitle: 'Better Gene Delivery for Canavan',
    brief: 'Testing novel AAV capsids evolved for superior white matter penetration to deliver the ASPA gene.',
    simpleBrief: 'Using a new "delivery truck" that is much better at getting the gene into the deep parts of the brain to cure Canavan Disease.',
    imagePrompt: 'A high-speed, futuristic molecular delivery vehicle (virus capsid) navigating through a dense neural forest, reaching deep targets. Dynamic motion.',
    category: 'Gene Therapy',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=800&q=80', // Brain
    researcher: {
      id: 'r26',
      name: 'Dr. Geoffrey Rush',
      title: 'Professor',
      institution: 'UMass Chan Medical School',
      avatarUrl: 'https://picsum.photos/id/91/200/200',
      verified: true,
    },
    fundingGoal: 140000,
    fundingRaised: 135000,
    backersCount: 290,
    milestonesCompleted: 3,
    totalMilestones: 4,
    milestones: ['Capsid Evolution', 'Primate Safety']
  },
  {
    id: 'p27',
    title: 'N-of-1 ASO Therapy for a Unique KIF1A Mutation',
    simpleTitle: 'A Custom Cure for One Child',
    brief: 'Developing a custom antisense oligonucleotide for a single child with a unique, gain-of-function mutation in KIF1A.',
    simpleBrief: 'Creating a custom drug designed from scratch for just one child’s specific genetic mutation.',
    imagePrompt: 'A single, glowing silhouette of a child, holding a unique, bright puzzle piece that fits perfectly into their heart/DNA. Symbolizing personalized medicine. Warm, emotional.',
    category: 'Disease Modeling',
    imageUrl: 'https://images.unsplash.com/photo-1616246395914-1e033d47b59e?auto=format&fit=crop&w=800&q=80', // Child/DNA
    researcher: {
      id: 'r27',
      name: 'Dr. Timothy Chang',
      title: 'Genomics Specialist',
      institution: 'Boston Children\'s Hospital',
      avatarUrl: 'https://picsum.photos/id/99/200/200',
      verified: true,
    },
    fundingGoal: 200000,
    fundingRaised: 198000,
    backersCount: 1500,
    milestonesCompleted: 2,
    totalMilestones: 2,
    milestones: ['Drug Design', 'FDA Single Patient IND']
  }
];

export const IMPACT_STATS: Stat[] = [
  { label: 'Lives Impacted', value: '2M+', subtext: 'Patients closer to a cure today' },
  { label: 'Researchers Supported', value: '1,200+', subtext: 'Top talent staying in the field' },
  { label: 'Productive Hours Saved', value: '450k+', subtext: 'Reclaimed from administrative burden' },
];