import React, { useState, useEffect } from 'react';
import { Project } from '../types';
import { BadgeCheck, Target, Users, ChevronRight, Wand2, Loader2, Sparkles } from 'lucide-react';
import { GoogleGenAI } from "@google/genai";
import { BACKUP_IMAGES } from '../constants';

interface ProjectCardProps {
  project: Project;
  onClick?: (project: Project) => void;
  mode?: 'simple' | 'technical';
}

export const ProjectCard: React.FC<ProjectCardProps> = ({ project, onClick, mode = 'technical' }) => {
  const percentComplete = Math.min((project.fundingRaised / project.fundingGoal) * 100, 100);

  const displayTitle = mode === 'simple' ? project.simpleTitle : project.title;
  const displayBrief = mode === 'simple' ? project.simpleBrief : project.brief;

  // Initialize with the default URL, but allow it to be overwritten by AI generation
  const [imgSrc, setImgSrc] = useState(project.imageUrl);
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);

  // Reset state if the project prop changes (e.g. in a list re-render)
  useEffect(() => {
    setImgSrc(project.imageUrl);
    setGenerated(false);
    setGenerating(false);
  }, [project.id, project.imageUrl]);

  const handleImageError = () => {
    // If the image fails to load, pick a random backup image to replace it.
    // This prevents broken images on the UI.
    const randomBackup = BACKUP_IMAGES[Math.floor(Math.random() * BACKUP_IMAGES.length)];
    // Only update if we aren't already using that specific backup to avoid potential (though rare) loops if backups fail too
    if (randomBackup !== imgSrc) {
        setImgSrc(randomBackup);
    }
  };

  const handleGenerateImage = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (generating || generated) return;

    setGenerating(true);
    try {
      const apiKey = process.env.API_KEY;
      if (!apiKey) {
        console.warn("No API Key available for image generation");
        // Simulate delay for UI testing if no key
        await new Promise(resolve => setTimeout(resolve, 2000));
        setGenerating(false);
        return;
      }

      const ai = new GoogleGenAI({ apiKey });
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            { text: project.imagePrompt || `A high quality scientific illustration of ${project.title}, ${project.brief}` },
          ],
        },
        config: {
          imageConfig: {
            aspectRatio: "4:3",
          },
        },
      });

      // Iterate through parts to find the image data
      if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            const base64EncodeString = part.inlineData.data;
            const newImageUrl = `data:image/png;base64,${base64EncodeString}`;
            
            // Immediate replacement
            setImgSrc(newImageUrl);
            setGenerated(true);
            break;
          }
        }
      }
    } catch (err) {
      console.error("Failed to generate image", err);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div 
      onClick={() => onClick && onClick(project)}
      className="glass-panel rounded-2xl overflow-hidden hover:border-nexus-accent/50 transition-all duration-300 group flex flex-col h-full cursor-pointer relative"
    >
      {/* Image Header */}
      <div className="relative h-48 overflow-hidden bg-gray-900 group-hover:shadow-[0_0_30px_rgba(56,189,248,0.2)] transition-shadow">
        <img 
          src={imgSrc} 
          alt={project.title} 
          onError={handleImageError}
          className={`w-full h-full object-cover transition-all duration-700 ${generating ? 'opacity-50 scale-105 blur-sm' : 'group-hover:scale-105 opacity-100 blur-0'}`}
        />
        
        {/* Category Badge */}
        <div className="absolute top-4 left-4 bg-nexus-dark/90 backdrop-blur-md px-3 py-1 rounded-full text-xs font-medium text-nexus-accent border border-nexus-accent/20 z-10">
          {project.category}
        </div>

        {/* Generate Button / Loader / Success Indicator */}
        <button
            onClick={handleGenerateImage}
            disabled={generating || generated}
            className={`absolute top-4 right-4 p-2 rounded-full backdrop-blur-md border transition-all z-20 group/btn shadow-lg
              ${generated 
                ? 'bg-nexus-secondary/20 border-nexus-secondary text-nexus-secondary cursor-default' 
                : 'bg-nexus-dark/60 hover:bg-nexus-accent hover:text-nexus-dark text-white border-white/10'
              }
            `}
            title={generated ? "Image Generated by AI" : "Visualize with AI"}
        >
            {generating ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : generated ? (
              <Sparkles className="w-4 h-4" />
            ) : (
              <Wand2 className="w-4 h-4" />
            )}
            <span className="sr-only">Generate AI Image</span>
        </button>
      </div>

      {/* Content */}
      <div className="p-6 flex flex-col flex-grow">
        <div className="flex items-center gap-3 mb-4">
          <img 
            src={project.researcher.avatarUrl} 
            alt={project.researcher.name} 
            className="w-10 h-10 rounded-full border border-gray-700"
          />
          <div className="flex flex-col">
            <span className="text-sm font-semibold text-white flex items-center gap-1">
              {project.researcher.name}
              {project.researcher.verified && <BadgeCheck className="w-4 h-4 text-nexus-secondary" />}
            </span>
            <span className="text-xs text-nexus-muted truncate max-w-[200px]">{project.researcher.institution}</span>
          </div>
        </div>

        <h3 className="text-xl font-bold text-gray-100 mb-3 leading-snug group-hover:text-nexus-accent transition-colors">
          {displayTitle}
        </h3>
        
        <p className="text-sm text-gray-400 mb-6 line-clamp-3 flex-grow">
          {displayBrief}
        </p>

        {/* Funding Status */}
        <div className="mt-auto space-y-4">
          <div className="w-full bg-gray-800 rounded-full h-2 overflow-hidden">
            <div 
              className="bg-gradient-to-r from-nexus-accent to-nexus-secondary h-full rounded-full transition-all duration-1000"
              style={{ width: `${percentComplete}%` }}
            />
          </div>
          
          <div className="flex justify-between items-end">
            <div>
              <div className="text-2xl font-bold text-white">
                ${project.fundingRaised.toLocaleString()}
              </div>
              <div className="text-xs text-gray-500">
                raised of ${project.fundingGoal.toLocaleString()}
              </div>
            </div>
            <div className="text-right">
              <div className="text-sm font-medium text-white">{Math.round(percentComplete)}%</div>
            </div>
          </div>

          <div className="pt-4 border-t border-gray-800 flex justify-between items-center text-xs text-gray-400">
            <div className="flex items-center gap-1">
              <Users className="w-4 h-4" />
              <span>{project.backersCount} backers</span>
            </div>
            <div className="flex items-center gap-1.5 text-nexus-secondary">
              <Target className="w-4 h-4" />
              <span className="font-medium">{project.milestonesCompleted}/{project.totalMilestones} Milestones Met</span>
            </div>
          </div>
        </div>
      </div>
      
      <div className="bg-nexus-accent/5 p-3 text-center text-nexus-accent text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center gap-2">
        View Research Proposal <ChevronRight className="w-4 h-4" />
      </div>
    </div>
  );
};